name: check

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Set NPM Variables
        run: echo "$PACKAGES_NPMRC" > .npmrc
        env:
          PACKAGES_NPMRC: ${{ secrets.PACKAGES_NPMRC }}
      - name: Install
        run: yarn install --ignore-engines
      - name: Local Linter
        run: yarn lint
      - name: Build
        run: yarn build
