name: check

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set NPM Variables
        run: echo "$PACKAGES_NPMRC" > .npmrc
        env:
          PACKAGES_NPMRC: ${{ secrets.PACKAGES_NPMRC }}
      - name: Install
        uses: borales/actions-yarn/@v2.3.0
        with:
          cmd: install --ignore-engines
      - name: Linter
        uses: borales/actions-yarn/@v2.3.0
        with:
          cmd: lint
      - name: Build
        uses: borales/actions-yarn/@v2.3.0
        with:
          cmd: build
