name: check

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn/@v2.0.0
        with:
          cmd: install --ignore-engines
      - name: Build
        uses: borales/actions-yarn/@v2.0.0
        with:
          cmd: build
