name: testing

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set NPM Variables
        run: echo "$PACKAGES_NPMRC" > .npmrc
        env:
          PACKAGES_NPMRC: ${{ secrets.PACKAGES_NPMRC }}
      - name: Install
        run: yarn install --ignore-engines
      - name: Build
        run: yarn build
      - name: Run jest tests
        run: yarn test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #

